### ISSUE TITLE
Idea: Regional Resources

### ISSUE THREAD

**Issue by kurucu** [tapyu/awesome-stem-academy#1]
What are your thoughts on contributions for regional resources, like charities, school support, extra-curricular clubs, etc?

It would have to break the rules a bit, e.g. top-level heading "Awesome Regional", with sub-headings per-country or similar?

**Comment by tapyu** [comment]
Hi! Firstly, thank you for getting involved. I am not sure if I understood what you mean by "regional resources". As far as I understand by charities, it has absolutely nothing to do with this awesome list. "Sub-headings per-country" made no sense for me, if you can give a link example, it would be nce.

**Comment by kurucu** [comment]
Ouch ;)

I was thinking things like this: https://www.stem.org.uk

**Comment by tapyu** [comment]
This suggestion has no adherence with this awesome list.
